<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-02T18:53:23 EDT" name="Suite" finished-at="2022-06-02T18:54:12 EDT" duration-ms="49309">
    <groups>
    </groups>
    <test started-at="2022-06-02T18:53:23 EDT" name="Test" finished-at="2022-06-02T18:54:12 EDT" duration-ms="49309">
      <class name="com.salesforcepom.Tests.POMFiveTestCases">
        <test-method is-config="true" signature="initialTestSetup()[pri:0, instance:com.salesforcepom.Tests.POMFiveTestCases@48e1f6c7]" started-at="2022-06-02T18:53:23 EDT" name="initialTestSetup" finished-at="2022-06-02T18:53:23 EDT" duration-ms="147" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialTestSetup -->
        <test-method is-config="true" signature="getDriver(java.lang.String,java.lang.reflect.Method)[pri:0, instance:com.salesforcepom.Tests.POMFiveTestCases@48e1f6c7]" started-at="2022-06-02T18:53:23 EDT" name="getDriver" finished-at="2022-06-02T18:53:31 EDT" duration-ms="8131" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public static void com.salesforcepom.Tests.POMFiveTestCases.testCase1() throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getDriver -->
        <test-method signature="testCase1()[pri:0, instance:com.salesforcepom.Tests.POMFiveTestCases@48e1f6c7]" started-at="2022-06-02T18:53:31 EDT" name="testCase1" finished-at="2022-06-02T18:53:38 EDT" duration-ms="7000" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase1 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.salesforcepom.Tests.POMFiveTestCases@48e1f6c7]" started-at="2022-06-02T18:53:38 EDT" name="tearDown" finished-at="2022-06-02T18:53:39 EDT" duration-ms="219" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="getDriver(java.lang.String,java.lang.reflect.Method)[pri:0, instance:com.salesforcepom.Tests.POMFiveTestCases@48e1f6c7]" started-at="2022-06-02T18:53:39 EDT" name="getDriver" finished-at="2022-06-02T18:53:40 EDT" duration-ms="1596" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public static void com.salesforcepom.Tests.POMFiveTestCases.testCase2() throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getDriver -->
        <test-method signature="testCase2()[pri:0, instance:com.salesforcepom.Tests.POMFiveTestCases@48e1f6c7]" started-at="2022-06-02T18:53:40 EDT" name="testCase2" finished-at="2022-06-02T18:53:55 EDT" duration-ms="15271" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Welcome to free trial] but found [Getting Started]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Welcome to free trial] but found [Getting Started]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.salesforcepom.Tests.POMFiveTestCases.testCase2(POMFiveTestCases.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.salesforcepom.Tests.POMFiveTestCases@48e1f6c7]" started-at="2022-06-02T18:53:55 EDT" name="tearDown" finished-at="2022-06-02T18:53:56 EDT" duration-ms="214" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="getDriver(java.lang.String,java.lang.reflect.Method)[pri:0, instance:com.salesforcepom.Tests.POMFiveTestCases@48e1f6c7]" started-at="2022-06-02T18:53:56 EDT" name="getDriver" finished-at="2022-06-02T18:53:59 EDT" duration-ms="2963" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public static void com.salesforcepom.Tests.POMFiveTestCases.testCase3() throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getDriver -->
        <test-method signature="testCase3()[pri:0, instance:com.salesforcepom.Tests.POMFiveTestCases@48e1f6c7]" started-at="2022-06-02T18:53:59 EDT" name="testCase3" finished-at="2022-06-02T18:54:12 EDT" duration-ms="13189" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Welcome to free trial] but found [Getting Started]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Welcome to free trial] but found [Getting Started]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.salesforcepom.Tests.POMFiveTestCases.testCase3(POMFiveTestCases.java:82)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase3 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.salesforcepom.Tests.POMFiveTestCases@48e1f6c7]" started-at="2022-06-02T18:54:12 EDT" name="tearDown" finished-at="2022-06-02T18:54:12 EDT" duration-ms="194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="finalTestTearDown()[pri:0, instance:com.salesforcepom.Tests.POMFiveTestCases@48e1f6c7]" started-at="2022-06-02T18:54:12 EDT" name="finalTestTearDown" finished-at="2022-06-02T18:54:12 EDT" duration-ms="337" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finalTestTearDown -->
      </class> <!-- com.salesforcepom.Tests.POMFiveTestCases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
